
version: '3'
services:
  nifi:
    build:
      context: .
      dockerfile: ./nifi/Dockerfile-nifi
    ports:
      - "8446:8446"


  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile-mysql
    environment:
      MYSQL_DATABASE: sample_data
      MYSQL_USER: architrave
      MYSQL_PASSWORD: 11111
    ports:
      - "3307:3307"
